services:
   mysqldb:
     container_name: mysqldb
     image: mysql
     ports:
       - 3307:3306
     environment:
       MYSQL_DATABASE: techplatform
       MYSQL_ROOT_PASSWORD: 011832Dd@

   springboot-app:
     image: techplatform-be
     restart: always
     build: .
     ports:
       - 8080:8080
     environment:
       MYSQL_HOST: mysqldb
       MYSQL_DB: techplatform
       MYSQL_PORT: 3306
       MYSQL_USER: root
       MYSQL_PASSWORD: 011832Dd@